### ISSUE TITLE
Game launch status: 'JAVA_HOME environment variable is required to run HDOS'

### ISSUE THREAD

**Issue by aestheticjmack** [Adamcake/Bolt#11]
I've been using bolt just fine for months, installed from the AUR, but now I'm getting the following errors when trying to launch HDOS. I did a complete reinstall and it's still giving me the error.

```
Game launch status: 'JAVA_HOME environment variable is required to run HDOS'

Latest JAR is already installed
```

**Comment by Adamcake** [comment]
Hi, as the error says, the JAVA_HOME variable needs to be set in your environment to launch HDOS. This would normally happen by automatically adding it to `/etc/profile` when you install Java, but you can set it yourself just fine. I think it's usually something like `JAVA_HOME=/usr/lib/jvm/java-xxxxxxxx` (find out what directory names exist there - it will depend on what Java versions you have installed)

**Comment by aestheticjmack** [comment]
Thank you, that fixed it up for me, still a bit of a linux noob, appreciate the help as always!!

**Comment by vaisest** [comment]
> Hi, as the error says, the JAVA_HOME variable needs to be set in your environment to launch HDOS. This would normally happen by automatically adding it to `/etc/profile` when you install Java, but you can set it yourself just fine. I think it's usually something like `JAVA_HOME=/usr/lib/jvm/java-xxxxxxxx` (find out what directory names exist there - it will depend on what Java versions you have installed)

Should this really be necessary? I'm using your AUR package and encountered this error since Arch does not set `JAVA_HOME` at all. For example:

```
user@pc ~$ sudo archlinux-java set java-21-openjdk
user@pc ~ $ echo $JAVA_HOME

```
Arch only uses `PATH` as far as I'm aware.
