### ISSUE TITLE
java.lang.RuntimeException: Assertions are not enabled, add '-ea' to your VM options

### ISSUE THREAD

**Issue by Robert-Rendell** [Adamcake/Bolt#13]
Using custom jar from bolt:
![Screenshot from 2024-01-07 01-30-46](https://github.com/Adamcake/Bolt/assets/11077105/12785b3a-04fd-4e46-8a68-b4f62878bafc)

Error when running:
![Screenshot from 2024-01-07 01-31-21](https://github.com/Adamcake/Bolt/assets/11077105/cbf1ac59-c111-4f10-8e2b-36ae2c9e84c3)

I can replicate this error by omitting the "-ea" flag:
`$ java -jar runelite-plugin-development.jar"

**Comment by Robert-Rendell** [comment]
I don't have any assertions in my java code

**Comment by Robert-Rendell** [comment]
![image](https://github.com/Adamcake/Bolt/assets/11077105/82a660c8-0466-45a9-aa02-a589749b3a5b)

**Comment by Robert-Rendell** [comment]
![Screenshot from 2024-01-07 02-43-55](https://github.com/Adamcake/Bolt/assets/11077105/f04bd789-e00c-406a-9f5e-8caa31cbb3e5)

**Comment by Adamcake** [comment]
That should be fixable by setting `_JAVA_OPTIONS="-ea"` in your env when running Bolt?

I'm not familiar with runelite plugin development, what's this jar file you're trying to run? Is it a custom build or did you get it from somewhere? It might be that it's a build of the runelite game client, whereas Bolt expects to be running the launcher.

**Comment by Robert-Rendell** [comment]
![image](https://github.com/Adamcake/Bolt/assets/11077105/4e87788d-f6c0-4068-b5f6-11ec094ee7ea)

**Comment by Robert-Rendell** [comment]
> That should be fixable by setting `_JAVA_OPTIONS="-ea"` in your env when running Bolt?
> 
> I'm not familiar with runelite plugin development, what's that jar file you're trying to run? Is it a custom build or did you get it from somewhere? It might be that it's a build of the runelite game client, whereas Bolt expects to be running the launcher.

Ok so it sounds like the setting on Bolt called "Use custom RuneLite JAR", isn't what I was expecting it to be.
To replay what you said, that field on Bolt is expecting a jagex launcher jar and not a runelite client jar (the latter is what I'm using).

![image](https://github.com/Adamcake/Bolt/assets/11077105/9df3f078-270f-41df-a15f-51fb3dd0ac47)

**Comment by Robert-Rendell** [comment]
I'll have a go of making my own build of the launcher.
Any modifications that are strikingly obvious to you to get me started?

**Comment by Robert-Rendell** [comment]
![image](https://github.com/Adamcake/Bolt/assets/11077105/d2726b8a-72c2-4cca-8fb1-df8a5f9a950e)

**Comment by Adamcake** [comment]
I meant a custom build of [runelite's launcher](https://github.com/runelite/launcher) not Bolt. Runelite has separate JAR files for its launcher and its client.

**Comment by Robert-Rendell** [comment]
Are there any instructions for building runelite's launcher?
![image](https://github.com/Adamcake/Bolt/assets/11077105/2b5cafc2-3a5b-4a19-ad75-b72ae400d35b)

**Comment by Robert-Rendell** [comment]
Thanks for all your help @Adamcake. I've created an issue on runelite launcher repo. Closing this issue since there are no modifications required to Bolt to get my runelite client jar working.
