### ISSUE TITLE
No audio in runelite client

### ISSUE THREAD

**Issue by mitburr** [Adamcake/Bolt#17]
When launching Runelite through the Bolt launcher, my client doesn't have audio. Standalone, runelite does at least have audio on the login screen (the music), but when launched via Bolt there is not even an audio stream listen in Pulseaudio. I do have the pulseaudio-alsa package installed. Let me know where I can find useful logs for y'all to help solve this issue. I'm running Arch Linux, and it is updated as of today. 

Attached is a txt file of the logs output in a shell running bolt from start until the launcher is opened. It looks like the symlink Pulse errors might be a good place to start. 

Thanks for your help!
[boltLaunchLogs2024-01-24.txt](https://github.com/Adamcake/Bolt/files/14045355/boltLaunchLogs2024-01-24.txt)

**Comment by Adamcake** [comment]
Looks same as #12?

**Comment by mitburr** [comment]
Lit that worked, thanks @Adamcake. Have you raised this issue to pulse?

**Comment by Adamcake** [comment]
No I haven't. Looking at the source code it looks like an easy fix, maybe I'll PR them later.
