### ISSUE TITLE
Allow client arguments or add an option to dump authentication tokens

### ISSUE THREAD

**Issue by furfy** [Adamcake/Bolt#20]
An important feature for the plugin development.
Currently there is no way to pass the `--insecure-write-credentials` argument to the client, which makes not possible to dump the `credentials.properties` file required for login without the Jagex Launcher.

Or at least I do not know how to do it right now.

**Comment by Adamcake** [comment]
I'm in the process of publishing a version which will allow you to use RuneLite's --configure option for options like that. Or you could also find the JX variables by launching the game via Bolt, finding the process with `ps`, then parsing `/proc/<pid>/environ`.

**Comment by furfy** [comment]
Works really well, thank you!

**Comment by dginovker** [comment]
Fwiw the format of `credentials.properties` is

```
JX_SESSION_ID=xyz
JX_CHARACTER_ID=123
X_DISPLAY_NAME=Lemmy
```

**Comment by dginovker** [comment]
Since I found myself doing this again, and the above format didn't include all the needed variables, I made a Bash one-liner that just populates the file for me.

Steps:

1. Run Runelite _from Bolt_
2. Paste this command in the terminal:

```bash
ps x | grep -i .runelite | grep -v grep | awk '{print $1}' | \
while read pid; do \
  tr '\0' '\n' < /proc/$pid/environ > ~/.runelite/credentials.properties; \
done
```
