### ISSUE TITLE
How is var "s" injected into launcher.js

### ISSUE THREAD

**Issue by thepure12** [Adamcake/Bolt#22]
I was looking at launcher.js to try to understand how it works, but I am not seeing where the variable/function "s" comes from.

**Comment by Adamcake** [comment]
It's defined in CEF's handlers. This deliberately obtuse, just to slightly improve my chances in case some first-party lawyers turn up.

The function is defined here:
https://github.com/Adamcake/Bolt/blob/master/src/browser/app.cxx#L42
And the handler is here:
https://github.com/Adamcake/Bolt/blob/master/src/browser/app.cxx#L109-L128
The launcher's onload event is to call `start(s())`, where the parameter is the variable called `s` in the rest of the code.

Don't spend too much time in app.cxx. CEF's render process implementation doesn't make any sense.

**Comment by thepure12** [comment]
Awesome thanks.
