### ISSUE TITLE
Invisible Window [Wayland/NVIDIA]

### ISSUE THREAD

**Issue by bashuser30** [Adamcake/Bolt#26]
Hello,

I am using Arch Linux with Bolt installed from the AUR. I have recently updated my system and now whenever I launch Bolt the window is invisible. Below is a screenshot of the window and output from launching it in the terminal. It works fine on X so it might be some weird new NVIDIA bug on Wayland. Let me know if you need more info provided.

Kernel: 6.7.5-arch1-1
OS: Gnome 45.4
NVIDIA Driver: 545.29.06

```
$ bolt
[0222/103545.463725:WARNING:chrome_browser_cloud_management_controller.cc(87)] Could not create policy manager as CBCM is not enabled.
[B] OnContextInitialized
[B] Browser::Window popup constructor, this=106430610144080
[B] OnWindowCreated 0 this=106430610144080
[B] OnAfterCreated for browser 1
[B] OnBrowserCreated this=106430610144080 1
[R] OnBrowserCreated for browser 1
MESA-LOADER: failed to open nvidia-drm: /usr/lib/gbm/nvidia-drm_gbm.so: cannot open shared object file: Permission denied (search paths /usr/lib/gbm, suffix _gbm)
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open nvidia-drm: /usr/lib/dri/nvidia-drm_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/dri, suffix _dri)
MESA-LOADER: failed to open kms_swrast: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/dri, suffix _dri)
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/dri, suffix _dri)
[R] OnLoadEnd for browser 1
[0222/103545.659410:ERROR:ev_root_ca_metadata.cc(161)] Failed to decode OID: 0
```

![Screenshot from 2024-02-22 10-36-30](https://github.com/Adamcake/Bolt/assets/147356887/fff155d6-4b3e-454f-bceb-a4858add1858)

**Comment by Adamcake** [comment]
First time I've seen that, but I'm not surprised - Wayland+Nvidia is notoriously bad. You could try running with `--disable-gpu --disable-gpu-compositing` to bypass Nvidia entirely (hopefully). Otherwise use X11 or upgrade to AMD.

**Comment by bashuser30** [comment]
> First time I've seen that, but I'm not surprised - Wayland+Nvidia is notoriously bad. You could try running with `--disable-gpu --disable-gpu-compositing` to bypass Nvidia entirely (hopefully). Otherwise use X11 or upgrade to AMD.

Unfortunately those flags didn't help. Feel free to close this issue. I'll update it with a comment if I find a fix or if it randomly gets fixed on the next NVIDIA update...

**Comment by bashuser30** [comment]
I enabled the extra-testing repository and installed the 550 NVIDIA driver and Bolt is now working on NVIDIA + Wayland.

**Comment by qverkk** [comment]
@bashuser30 are your rs clients using the nvidia gpu though? in nvtop, bolt is using the nvidia gpu, but rs3/osrs clients are being ran on the igpu for me

**Comment by bashuser30** [comment]
@qverkk I'm not familiar with nvtop's output, but it seems like it's using the GPU. The screenshot below is with 2 Runelite clients and Bolt opened. I'm also fairly certain my iGPU is disabled.

![image](https://github.com/user-attachments/assets/6beb1e78-131f-4df0-903a-4ddf4e99798f)
