### ISSUE TITLE
Launcher does not close correctly

### ISSUE THREAD

**Issue by WRakocki** [Adamcake/Bolt#27]
After closing the launcher the process is not killed. To open the launcher again you need to kill the process manually.

**Comment by Adamcake** [comment]
You're meant to close it by the tray icon. I intend to remove the tray icon
and gtk dependency so that the process will just stop automatically when no
longer depended on, but it's going to take a while to get there - the RS3
plugin library will need to use Bolt as a browser host.

**Comment by WRakocki** [comment]
I am using stock gnome right now so I don't actually have app tray and I thought it was some kind of bug. If so, I am closing the issue.  Keep up the good work!
