### ISSUE TITLE
How to customize RuneLite's launch options?

### ISSUE THREAD

**Issue by 1player** [Adamcake/Bolt#3]
I'm using the Flatpak version of Bolt and works great, but I need to customize its launch options -- namely, passing `--scale=2` because otherwise it is too small on my 4K screen, and I see no way of doing that in bolt.

**Comment by Adamcake** [comment]
No way to do that via the interface at the moment, but I could easily add it to the settings area. Do you know of any other launch options that'd be worth adding at the same time?

**Comment by 1player** [comment]
That's the only one I need in GNOME, but I know some users in Sway need to set custom environment variables, see: https://old.reddit.com/r/swaywm/comments/ysg6yx/runelite_wont_stretch_in_sway_but_works_fine_in/

I think the easiest way for you is to call a script that spawn RuneLite rather than spawning Runelite directly, so people can customize the launch options without having to create custom UI. A bit like the Jagex Launcher script for Lutris does: https://github.com/TormStorm/jagex-launcher-linux/blob/main/resources/runelite.sh

**Comment by Adamcake** [comment]
Environment variables for Bolt and its subprocesses can be set in flatseal, or by running `flatpak` with one or more `--env` switches. Or of course they can be added to the actual env if not using Flatpak. We could also add a customisable list of environment variables to the Bolt UI.

Custom launch scripts would be possible with some effort, but would present some sandboxing issues and would not be cross-platform, so I'm not keen to go that route.

**Comment by Adamcake** [comment]
This seems to work, although runelite itself doesn't seem very versatile with the setting: it only accepts whole numbers and doesn't allow resizing the window when the scale is above 1. Hopefully that's correct and not a mistake I've made. Anyway, this will be in the next release.

**Comment by 1player** [comment]
I only need scale 2. Thanks, looking forward to trying it out.

**Comment by Adamcake** [comment]
Added in 0.3 which I've just rolled out today. Assuming you installed via flatpak, give it a day or two, then run `flatpak update`.

**Comment by minh-v** [comment]
The scaling setting works great, but I'm encountering an issue where when my mouse pointer moves over the Runelite client, it "unscales" itself. Did you deal with something similar? @1player
