### ISSUE TITLE
There was an error loading the game configuration from the website.

### ISSUE THREAD

**Issue by VlaK0r** [Adamcake/Bolt#32]
![image](https://github.com/Adamcake/Bolt/assets/77666575/afd3f86d-bd67-4c5c-8aa0-e07a798379c3)

![image](https://github.com/Adamcake/Bolt/assets/77666575/a9d78802-6424-413c-a6f2-fec2eb83f4b8)

**Comment by Adamcake** [comment]
The game's currently down for planned maintenance, as I guess you already figured out.
