### ISSUE TITLE
RS3 Can't Launch on Archlinux

### ISSUE THREAD

**Issue by tilkinsc** [Adamcake/Bolt#37]
Arch btw

Ryzen 9 3900x
Rx 6900 xt

```
yay -S bolt-launcher
bolt
```

I was able to log in successfully. The first time I clicked download it downloaded and installed. It printed out `Game launch status: 'OK'` and has a bunch of bolt processes hanging (probably from chromium). A process named `rs3linux` is present but is looks like its hung up doing nothing.

```
[mkp@arch ~]$ bolt
[0419/021119.651473:WARNING:chrome_browser_cloud_management_controller.cc(87)] Could not create policy manager as CBCM is not enabled.
[0419/021119.653366:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[0419/021119.653409:WARNING:property.cc(144)] version: GetAndBlock: failed.
[0419/021119.653435:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
[0419/021119.653483:WARNING:gtk_ui.cc(143)] Unexpected gtk-xft-rgba "rgba"
[B] OnContextInitialized
[B] Browser::Window popup constructor, this=111131796055424
[B] OnWindowCreated 0 this=111131796055424
[B] OnAfterCreated for browser 1
[B] OnBrowserCreated this=111131796055424 1
[0419/021119.759551:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
[R] OnBrowserCreated for browser 1
[R] OnLoadEnd for browser 1
[0419/021119.889887:ERROR:ev_root_ca_metadata.cc(161)] Failed to decode OID: 0
[B] Successfully spawned game process with pid 1301
/home/mkp/.local/share/bolt-launcher/rs3linux: error while loading shared libraries: libgdk-x11-2.0.so.0: cannot open shared object file: No such file or directory
```

/lib and /usr/lib (but not /usr/local/lib) has:
```
./libgdk_pixbuf-2.0.so.0
./libgdk-3.so.0.2409.32
./libgdk_pixbuf-2.0.so
./libgdk-3.so
./libgdk-3.so.0
./libgdk_pixbuf-2.0.so.0.4200.10
```

So it's understandable that rs3linux couldn't find libgdk-x11-2.0.so.0
Progress was made with `yay -S libgtk2`

Getting the issue with openssl 1.1 not being found.
Attempting to `yay -S openssl-1.1`

Okay its splash screening.
Signing in feels very loady, expected.
Logging in to play. [Loading - please wait.] :tm: 

My issue was resolved with,
```
yay -S libgtk2 openssl-1.1
```

# Proposal
* Add section for libgtk2 issue since this is a very vanilla install of x11 arch on cinnamon, if other can me too this
* Add section promoting [sdkman](https://sdkman.io/) instead of using the aur jdk17, as its nicely packaged and contains actually modern releases while not stealing your JAVA_HOME and masking your /usr/bin/java
```
curl -s "https://get.sdkman.io" | bash
source \"~/.sdkman/bin/sdkman-init.sh\""
sdk install java 21.0.2-tem

# you can swap java versions easily via
# sdk use java 21.0.2-tem

# [mkp@arch lib]$ which java
# /home/mkp/.sdkman/candidates/java/21.0.2-tem/bin/java
# [mkp@arch lib]$ echo $JAVA_HOME
# /home/mkp/.sdkman/candidates/java/21.0.2-tem
```

**Comment by Adamcake** [comment]
libgtk2 and openssl-1.1 are listed as optdepends for 'rs3' in the AUR package. For oldschool, installing any Java version is fine, but I don't think there's a good way of conveying that in opedepends because it needs a specific package name.

**Comment by tilkinsc** [comment]
You're right. They are listed as optdepends. Which I would discover through the AUR website, `pacman -Qi bolt-launcher` or `yay -Si bolt-launcher`. I wonder if its better to disable rs3 functionality through bolt-launcher, informing users can download these optdepends to activate it.

**Comment by Adamcake** [comment]
There's no easy way for Bolt to check this unfortunately. I'd have to do a load of PATH searching which would noticeably slow down the launch. I think I'll just have to rely on arch users to read the optdepends.
