### ISSUE TITLE
AUR package?

### ISSUE THREAD

**Issue by lvctr** [Adamcake/Bolt#4]
Hi, are there any plans for an AUR package for Arch users? Thanks!

**Comment by Adamcake** [comment]
I do intend to publish on more package managers including AUR, but for now the only options are flatpak or building and installing from source.

**Comment by Adamcake** [comment]
I've published the latest version on AUR under the name "bolt-launcher" https://aur.archlinux.org/packages/bolt-launcher

Note the optional dependencies: if you want to run runelite then you'll need to install Java, and if you want to run RS3 then you'll need `pacman -S gtk2 openssl-1.1`.

**Comment by AlfredoDinunzioTR** [comment]
> I've published the latest version on AUR under the name "bolt-launcher" https://aur.archlinux.org/packages/bolt-launcher
> 
> Note the optional dependencies: if you want to run runelite then you'll need to install Java, and if you want to run RS3 then you'll need `pacman -S gtk2 openssl-1.1`.

Thanks so much! I picked the perfect time to come back it seems like.
