### ISSUE TITLE
Flatpak version crashes on Fedora with KDE and KWallet

### ISSUE THREAD

**Issue by xanni3** [Adamcake/Bolt#45]
Recently switched from gnome-keyring to KWallet and the launcher seems to crash with KWallet

> flatpak run com.adamcake.Bolt                                            
> [0612/113252.667035:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [0612/113252.692614:WARNING:chrome_browser_cloud_management_controller.cc(87)] Could not create policy manager as CBCM is not enabled.
> [B] OnContextInitialized
> [B] Browser::Window popup constructor, this=94093377103840
> [B] OnWindowCreated 0 this=94093377103840
> [0612/113252.698804:ERROR:object_proxy.cc(590)] Failed to call method: org.kde.KWallet.isEnabled: object_path= /modules/kwalletd6: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
> [0612/113252.698832:ERROR:kwallet_dbus.cc(107)] Error contacting kwalletd6 (isEnabled)
> [0612/113252.698922:ERROR:object_proxy.cc(590)] Failed to call method: org.kde.KLauncher.start_service_by_desktop_name: object_path= /KLauncher: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
> [0612/113252.698929:ERROR:kwallet_dbus.cc(79)] Error contacting klauncher to start kwalletd6
> [0612/113252.698933:WARNING:key_storage_linux.cc(219)] OSCrypt tried KWallet but couldn't initialise.
> [0612/113252.698997:ERROR:object_proxy.cc(590)] Failed to call method: org.kde.KWallet.close: object_path= /modules/kwalletd6: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
> [0612/113252.699002:ERROR:kwallet_dbus.cc(459)] Error contacting kwalletd6 (close)
> [B] OnAfterCreated for browser 1
> [B] OnBrowserCreated this=94093377103840 1
> [R] OnBrowserCreated for browser 1
> [0612/113252.744109:WARNING:sandbox_linux.cc(401)] InitializeSandbox() called with multiple threads in process gpu-process.
> [R] OnLoadEnd for browser 1
> [0612/113252.792131:ERROR:ev_root_ca_metadata.cc(161)] Failed to decode OID: 0
> [0612/113255.015230:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
> [0612/113256.766576:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!

OS: Fedora Linux 40 x86_64
Kernel: Linux 6.8.11-300.fc40.x86_64
DE: KDE Plasma 6.0.5

**Comment by Adamcake** [comment]
KWallet errors are normal, and gnome-keyring support is turned off at build
time. Bolt doesn't need these features and these errors don't normally
prevent it from starting up. Are you saying it crashes, as in the process
exits after this point?

**Comment by xanni3** [comment]
Yes it crashes about 3-5 seconds after launch. Though actually I'm no longer sure if its a explicitly kwallet issue, I uninstalled kwallet and it still occurs though with the same error messages. It seems to happen on KDE. When swapping over to Hyprland or Gnome I don't experience this but also in those cases there are no kwallet errors.

**Comment by Adamcake** [comment]
Could the difference be x11 vs wayland?

**Comment by xanni3** [comment]
All DE's I've been using are on wayland so not in this case

**Comment by xanni3** [comment]
Okay looks like flatseal was the culprit the "Can run in the background" permission was off but for some reason on KDE if this was off it was causing a crash unlike the other DE's.
