### ISSUE TITLE
Use native .runelite directory in flatpak?

### ISSUE THREAD

**Issue by dakota-marshall** [Adamcake/Bolt#46]
Sorry if its a dumb question, but is it possible to have the flatpak version of RuneLite use the `~/.runelite` instead of `~/.var/app/com.adamcake.Bolt/data/bolt-launcher/.runelite`? 

This is mainly for easier access to screenshots, so otherwise is it possible to symlink the screenshot folder out into something like `~/Pictures/RuneLite` or something like that? I set up this symlink manually anyway, but not sure if it's possible in the flatpak setup natively.

**Comment by Adamcake** [comment]
You can set this up manually using symlinks, but doing it in the flatpak
repo would be against flathub's app requirements:

"Do not attempt to retain configs from non-flatpak installations. While
possible it is recommended that flatpak installs stay self-contained."

https://docs.flathub.org/docs/for-app-authors/requirements/

Bolt takes several steps to make sure games save their config in a
self-contained xdg-compliant location. If you want to change that, that's
up to you - symlinks would be the ideal way to do it.

**Comment by dakota-marshall** [comment]
Makes sense, I figured that might be the reason. Figured I'd ask though, thanks for the quick feedback!

And yea I did setup the symlinks myself, so its all good there.
