### ISSUE TITLE
CMake Error on Windows

### ISSUE THREAD

**Issue by ExemplaryFF** [Adamcake/Bolt#49]
I've tried following the README steps for a windows build but am receiving the following error when executing 
`cmake -S . -B build -G "Visual Studio 17"`

```PS D:\Dev\Bolt> cmake -S . -B build -G "Visual Studio 17"
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.26100.
CMake Error at CMakeLists.txt:371 (target_include_directories):
  Cannot specify include directories for target "bolt-plugin" which is not
  built by this project.


CMake Error at CMakeLists.txt:372 (target_link_libraries):
  Cannot specify link libraries for target "bolt-plugin" which is not built
  by this project.


-- Configuring incomplete, errors occurred!```

**Comment by Adamcake** [comment]
It's been quite a while since I tried to get this to build on Windows. In this case, I think you could just specify `-D BOLT_SKIP_LIBRARIES=1` in the command. That would mean the plugin library won't be built, but that's nowhere near being able to work on Windows, anyway.

**Comment by FakeDisciple** [comment]
Literally get the same error on Debian
Debian GNU/Linux 12 (bookworm) x86_64 
Host: 82N6 Legion 7 16ACHg6 
Kernel: 6.1.0-22-amd64  
Packages: 1641 (dpkg), 10 (flatpak) 
Shell: bash 5.2.15 
Resolution: 2560x1600 
DE: lightdm-xsession 
WM: i3 
Theme: dracula [GTK2/3] 
Icons: Dracula [GTK2/3] 
Terminal: terminator 
CPU: AMD Ryzen 7 5800H with Radeon Graphics (16) @ 3.200GHz 
GPU: NVIDIA GeForce RTX 3080 Mobile / Max-Q 8GB/16GB 
Memory: 3138MiB / 64153MiB

**Comment by Adamcake** [comment]
Windows builds now work correctly with or without the plugin library so closing this.
