### ISSUE TITLE
Is this safe?

### ISSUE THREAD

**Issue by lukitsche** [Adamcake/Bolt#5]
Is it safe to use the launcher?
Sorry for the question, but are my passwords safe?

**Comment by charlesalec** [comment]
I can vouch for it, I've been using it for a while now. Plus the source is open, it doesn't seem to have any non-intended behavior.

**Comment by Adamcake** [comment]
Yes, your passwords are safe. Bolt Launcher works the same way as the official launcher, in that it doesn't directly handle any of your login details. It just opens the login website in a browser window and then waits.
