### ISSUE TITLE
Minor bug: unable to launch RuneLite on Fedora 39 after adding a new character on first launch

### ISSUE THREAD

**Issue by ajaypillay** [Adamcake/Bolt#52]
This happened when I did a specific sequence of actions on Fedora 39. I added a new character to my account while the launcher was open and I was logged in, then I closed and re-opened the launcher. When I tried to launch the RuneLite client on my new character, the following error was shown:
```
Error from https://api.github.com/repos/runelite/launcher/releases: 0:
```
I tried this on all the characters on my account, and the same error was thrown when attempting to launch RuneLite. HDOS didn't work either (though I didn't record the error message).

Re-launching the client seemed to fix this and RuneLite works now. Just figured I'd report it anyway.

**Comment by Adamcake** [comment]
The error would suggest you didn't have an Internet connection at the time,
or maybe some DNS level outage.

**Comment by ajaypillay** [comment]
I did have a connection as I was accessing the rest of the Internet via my web browser, and I was also logged in to another character on RS3. I visited the API link as well via my browser to verify that it was accessible too.

**Comment by Adamcake** [comment]
Possibly a one-time error in flatpak's sandboxing then? "0" in xml means a
non-http failure such as a connection timeout or a network failure. It
can't really mean anything else.

Let me know if it happens again or you can get it to happen consistently,
but currently this sounds very much like a transient one-time occurrence.

**Comment by ajaypillay** [comment]
Will do. I'll close this issue for now. If I'm able to reproduce it I'll report back. Thanks!
