### ISSUE TITLE
Notification Settings Force not working

### ISSUE THREAD

**Issue by jeff06** [Adamcake/Bolt#53]
Ubuntu 22.04 LTS

On osrs, using runelite, activating in the pluging "RuneLite" -> "Notification Settings" -> "Request focus" -> "Force" is not forcing the window on top. RuneLite is taking the focus, but stays under other window.

It should bring the window on top of every other window.

**Comment by Adamcake** [comment]
That would be more likely to be an issue with runelite than with bolt. As far as I can tell from runelite's code, the "Force" setting on linux doesn't actually do anything. Have you tried this with any launchers other than bolt?

**Comment by jeff06** [comment]
Hi!

I did try on a windows machine with the jagex launcher and it work.
So it might be a RuneLite bug for linux. I was just checking if someone had prior knowledge of this.

Thanks!

**Comment by Adamcake** [comment]
It seems runelite knows about this already: https://github.com/runelite/runelite/pull/15207, https://github.com/runelite/runelite/pull/16676

The exact behaviour probably varies on different desktop environments. But you'll have to ask them for more info.
