### ISSUE TITLE
[Feature Request] Exit on Game Launch

### ISSUE THREAD

**Issue by DarkArc** [Adamcake/Bolt#59]
It would be nice if the launcher closed itself after launching the game (or at least had the option).

Thanks :)

**Comment by dotaxis** [comment]
+1 would appreciate this <3

**Comment by psynt** [comment]
Vote against because if it doesn't, then I can launch two or more games on two or more characters

**Comment by dotaxis** [comment]
Adding this as an option would obviously not prevent you from doing that

**Comment by Adamcake** [comment]
Added in b7f0d1c

**Comment by dotaxis** [comment]
A rebuild from the AUR did not add this option for me.

**Comment by Adamcake** [comment]
That's because AUR is still building from the 0.9 release tag. The feature will be in the next release, probably in a couple of days.

**Comment by dotaxis** [comment]
Oh, I thought it grabbed the latest commit. I'll wait then, thanks :)

**Comment by Adamcake** [comment]
Version 0.10 out now - should be available on AUR already.
