### ISSUE TITLE
No release binaries

### ISSUE THREAD

**Issue by RuiNtD** [Adamcake/Bolt#60]
Hello. The Readme mentions going to releases for downloads, but there are no binaries in releases. Considering there are build instructions for Windows, I would assume there would at least be Windows binaries.

**Comment by Adamcake** [comment]
Bolt can be built for Windows however there are no official builds for Windows yet due to some features still missing. Mainly that it's not able to launch any osrs clients yet.

**Comment by Adamcake** [comment]
Official Windows binaries are in the releases section as of today's version 0.10
