### ISSUE TITLE
Launcher not usable during github outage?

### ISSUE THREAD

**Issue by Wgelyjr** [Adamcake/Bolt#61]
I'm assuming there's some logic for the launcher checking for an update?
Is there any way to not tie the launcher's functionality to the availability of github?

**Comment by Wgelyjr** [comment]
![image](https://github.com/user-attachments/assets/35ced397-55ca-48aa-93c6-bbe7e361e505)

**Comment by Wgelyjr** [comment]
I just realized it's checking for the latest runelite and I can probably fix this by specifying a custom runelite jar. leaving this as a monument to my ignorance.

**Comment by Adamcake** [comment]
Yeah it was a github outage. At some point I'll get round to making it able to launch games even if the update check fails.
