### ISSUE TITLE
Error logging in on a windows build

### ISSUE THREAD

**Issue by umer-rs** [Adamcake/Bolt#62]
This is the only error the launcher gives:

Error: from https://auth.jagex.com/game-session/v1/sessions: 0:

**Comment by Adamcake** [comment]
Probably an issue that was already fixed in
331f79a69d146a50a8c5e380ad536a2851335eca (and a few subsequent commits).
What commit is your build from?

**Comment by umer-rs** [comment]
Oh, it seems like me trying to build on the latest commit didn't succeed.

```
ipc_posix.obj : error LNK2019: unresolved external symbol __imp_recv referenced in function _bolt_ipc_receive [C:\Users\umer\Documents\Bolt\build\bolt.vcxproj]ipc_posix.obj : error LNK2019: unresolved external symbol __imp_send referenced in function _bolt_ipc_send [C:\Users\umer\Documents\Bolt\build\bolt.vcxproj]
ipc_posix.obj : error LNK2019: unresolved external symbol __imp_WSAPoll referenced in function _bolt_ipc_poll [C:\Users\umer\Documents\Bolt\build\bolt.vcxproj]
C:\Users\umer\Documents\Bolt\build\Release\bolt.exe : fatal error LNK1120: 3 unresolved externals [C:\Users\umer\Documents\Bolt\build\bolt.vcxproj]
```

**Comment by Adamcake** [comment]
Are you trying to build with plugins or without? (in other words, dis you
set BOLT_LUAJIT_DIR or BOLT_SKIP_LIBRARIES)

It looks like I accidentally included ipc_posix.c even if not using
plugins, that doesn't exactly explain your error though.

**Comment by Adamcake** [comment]
Oh, wait, yes it does - winsock2 functions declared but not linked. Thanks, I'll get that fixed shortly when I get home.

**Comment by Adamcake** [comment]
Oops, didn't expect that would close it. Does it build now?

**Comment by umer-rs** [comment]
Yup, thanks a lot for the quick investigation.
