### ISSUE TITLE
Character missing after 504 error.

### ISSUE THREAD

**Issue by Binarynova** [Adamcake/Bolt#63]
Launching Bolt this morning I got a 504 error and was not being logged in. I restarted my laptop, and tried again, and now I'm being logged in fine, but my character seems to be missing. My only option is "New Character".

![image](https://github.com/user-attachments/assets/680538df-35e9-43c7-bc57-9cd362825121)

**Comment by Adamcake** [comment]
There have been issues on jagex's side which started around 30 minutes ago,
so it's probably temporary. I'll check if it's still happening later (a few
people have reported this already) and if so I'll look into it.

**Comment by Binarynova** [comment]
It already seems to have cleared up on my end. Thank you!
