### ISSUE TITLE
Won't launch after libfmt update to version 11

### ISSUE THREAD

**Issue by Courie** [Adamcake/Bolt#67]
Trying to launch bolt-launcher gives me the error:
`./bolt: error while loading shared libraries: libfmt.so.10: cannot open shared object file: No such file or directory`

Downgrading to fmt version 10 fixes the issue, but is not ideal.

Using Arch Linux.

Thank you.

**Comment by Adamcake** [comment]
You need to rebuild Bolt. Bolt links libfmt.so using `-lfmt`, which, at the time when you installed Bolt, resolved to `libfmt.so.10`. So now you have a Bolt binary with a hard dependency on `libfmt.so.10`, even though that no longer exists on your system. Building it again will update those references.

Arch doesn't seem to have any solution to this problem, unfortunately.

**Comment by rcfox2** [comment]
uninstalling bolt with all its options seemed to work for this (arch linux), so `yay -Rn bolt-launcher` and then `yay -S bolt-launcher`

**Comment by Adamcake** [comment]
Someone on Discord said `yay -S --rebuild bolt-launcher` worked for them without having to uninstall. Don't know if all AUR helpers have the same option.

**Comment by Courie** [comment]
I updated fmt and rebuilt bolt using `paru -S --rebuild bolt-launcher`, works great. Thanks.
