### ISSUE TITLE
Flatpak package strange discord permission

### ISSUE THREAD

**Issue by HenningGideskog** [Adamcake/Bolt#69]
When running 

`flatpak info --show-permissions com.adamcake.Bolt`

for the 0.9.0 version I get 

```
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;
devices=dri;
filesystems=xdg-run/app/com.discordapp.Discord;xdg-data/icons:create;

[Session Bus Policy]
org.freedesktop.Notifications=talk

[Environment]
JAVA_HOME=/app/jre
```

And I the line I am worried about is 
>filesystems=xdg-run/app/com.discordapp.Discord;xdg-data/icons:create;

Why does the launcher have access to a directory that seemingly is for Discord? 

Thanks for this great launcher!

**Comment by Adamcake** [comment]
So that Runelite will have access to Discord's rich presence feature, if the user has enabled it.

**Comment by HenningGideskog** [comment]
Aha, that makes sense. Thanks for answering and once again, I really love the client!
