### ISSUE TITLE
After recent flatpak update, user data wiped

### ISSUE THREAD

**Issue by InfiniMax1** [Adamcake/Bolt#76]
For some reason my credentials are gone, and launching Bolt every time now gives me the popup "Bolt is an unofficial third party launcher, Jagex is not responsible ..." etc

I know I can enable file permissions in Flatseal but I tried that with Home files and didn't get anywhere, should I try something else?

**Comment by Adamcake** [comment]
The first time you opened Bolt after the update, you should've got a message about credentials being outdated and saying "please sign in again" (see image). That's because the UI was changed significantly with the update from 0.9 to 0.10, but it should only happen once. If you closed and re-opened the launcher after that then you'll get the disclaimer popup because that always appears if you have no credentials saved.

Does it work correctly after signing back in, or are you still getting that problem?

![image](https://github.com/user-attachments/assets/f2da1db4-95bf-4866-81d6-d3b16c260903)

**Comment by InfiniMax1** [comment]
> The first time you opened Bolt after the update, you should've got a message about credentials being outdated and saying "please sign in again" (see image). That's because the UI was changed significantly with the update from 0.9 to 0.10, but it should only happen once. If you closed and re-opened the launcher after that then you'll get the disclaimer popup because that always appears if you have no credentials saved.
> 
> Does it work correctly after signing back in, or are you still getting that problem?
> 
> ![image](https://private-user-images.githubusercontent.com/30269600/378067862-f2da1db4-95bf-4866-81d6-d3b16c260903.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzcxNDAsIm5iZiI6MTcyOTMzNjg0MCwicGF0aCI6Ii8zMDI2OTYwMC8zNzgwNjc4NjItZjJkYTFkYjQtOTViZi00ODY2LTgxZDYtZDNiMTZjMjYwOTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDExMjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMzMzYTJmOGY0YzdhOGRiNjAyNWExYzMzNmM1MjlhMzY4MDlhY2ViNWM3MWQ2NTcyMjA3MWRkNTc5ZDY4MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.imbpe7GXnlCKmfoS5S9lu3MpE2Zj6Z_gz5c4EL2SyME)

I was just able to sign in (previously had some issues with sending verification code via email), will let you know if the problem reoccurs

**Comment by InfiniMax1** [comment]
PS The reason I asked about Flatseal is if it's reading from home dot files I thought maybe a reason it wasn't loading anything is because it's disabled in Flatseal (I don't know exactly where the data is stored) and if it was maybe worthwhile to enable some permissions

**Comment by InfiniMax1** [comment]
Seems fixed now in any event

**Comment by Adamcake** [comment]
It shouldn't ever access the home directory, it uses XDG directory locations which flatpak correctly provides for.

Please re-open if it happens again, I don't think it will though.
