### ISSUE TITLE
arRPC doesn't function when using Runelite via Bolt

### ISSUE THREAD

**Issue by Kompreya** [Adamcake/Bolt#8]
I'm using a Linux distro - KDE - and use Armcord for my Discord alternative.

It makes use of an arRPC server to display Rich Presence info.

You can find more details here on how it works:

https://github.com/ArmCord/ArmCord

https://github.com/OpenAsar/arrpc

https://github.com/OpenAsar/arrpc/blob/main/examples/bridge_mod.js

With the arRPC server running and using the bridge_mod script, running the Runelite flatpak and/or jar by itself (without bolt) has Runelite show up in my Discord status as expected.

However, when launching it via Bolt, the status doesn't show.

It should be noted that I symlinked my old Runelite installation to where Bolt expects to find the .runelite folder in ~/.var/app/com.adamcake.Bolt/data/bolt-launcher/, but this shouldn't affect anything as that's just user settings.

I tried both using the bolt-included runelite jar, and setting the custom jar location from my previous installation.

Do I need to set something via flatseal for Bolt or otherwise to get this to work properly? Thanks

**Comment by Kompreya** [comment]
Understandable. I also noticed that when launching through Bolt, Runelite will not use KDE's notifications for notifs (such as level ups, completed timers, idle notifs, etc)
Again, this is despite pointing Bolt to the same jar file I used to launch prior to switching to Jagex, which I had ensured used KDE's notifications, so I believe there's actually a permission issue when using Bolt.

I decided to just switch to using Jagex launcher through Lutris, and opted away from Bolt, since it seems to respect my permission and sandboxing settings (notifs go to KDE notifs, arrpc connects, etc), so I won't be investigating this myself any further.

**Comment by Adamcake** [comment]
The notification issue would probably be down to the `--talk-name=org.freedesktop.Notifications` permission that the Runelite flatpak has, as well as it bundling libnotify version 0.8.2. That one should hopefully be a simple fix but I would need it confirmed by someone able to change flatseal settings and testing the result.

**Comment by Adamcake** [comment]
Bolt-Flatpak is now allowed to send notifications to the DE, and opt-in discord RPC is available since 0.7. Thanks for raising.
