### ISSUE TITLE
Using end-of-life dependencies

### ISSUE THREAD

**Issue by TheInfamousAlk** [Adamcake/Bolt#81]
I'm not sure if this is the right place for this report. Bolt in the flatpak flathub repository is currently using 3 dependencies which are end of life. It would be nice if we could use a newer version of those. See paste below of the notice every time I update flatpak:

> Info: runtime org.freedesktop.Platform branch 22.08 is end-of-life, with reason:
>    org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
> Info: applications using this runtime:
>    com.adamcake.Bolt
> 
> Info: runtime org.freedesktop.Platform.GL.default branch 22.08-extra is end-of-life, with reason:
>    org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
> Info: applications using this extension:
>    com.adamcake.Bolt
> 
> Info: runtime org.freedesktop.Platform.GL.default branch 22.08 is end-of-life, with reason:
>    org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
> Info: applications using this extension:
>    com.adamcake.Bolt

22.08 is end of life, the current version is 24.08. 
https://flathub.org/apps/org.freedesktop.Platform

**Comment by Adamcake** [comment]
Bolt was on 23.08 until a few days ago, but I had to downgrade to 22.08 due to #78. The upstream issue has apparently been fixed and is awaiting new releases of freedesktop-sdk. As soon as I have those fixed versions, I'll try to move it to 24.08. Until then, sorry, it was my only option.

**Comment by TheInfamousAlk** [comment]
Ah okay, no need to apologize at all. I completely understand. I'm glad you were already aware. Thank you for your hard work! I really appreciate Bolt :)

I'd be good with closing this issue since you already were aware, but I guess I'll leave it open for now in case anyone else searches for it/wants to report it.

**Comment by Adamcake** [comment]
Moved to 24.08
