### ISSUE TITLE
Notification bubble

### ISSUE THREAD

**Issue by Neidraidd** [Adamcake/Bolt#87]
App always shows 1 notification bubble, but I am unable to find what this is referring to or how to clear it? I have tried reinstalling and still remains. Also no updates available, not causing an issue but i'm not sure what its trying to tell me?

![Screenshot From 2024-11-25 09-48-32](https://github.com/user-attachments/assets/e457e9e8-a71d-418b-9f8c-3354c269e0dd)

**Comment by Adamcake** [comment]
I've never seen that before, what desktop environment are you using? It could be that your DE is putting a number there for some un-intuitive reason, like with this issue: https://github.com/micheleg/dash-to-dock/issues/1964

**Comment by Neidraidd** [comment]
Gnome latest, but you are correct issue is related to Dash to Dock. Disabling "Show the number of unread notifications" removed the +1 bubble but other apps still function as expected. Sorry for wasting your time but thanks for the assistance!

Also best OSRS launcher around :)

![Screenshot From 2024-11-25 12-39-01](https://github.com/user-attachments/assets/d6a81055-c075-45ae-95ad-77938352c426)
