### ISSUE TITLE
Runelite not starting on W10

### ISSUE THREAD

**Issue by EytanMorg** [Adamcake/Bolt#96]
I get the 2 errors below after pressing Play while having the client set on RuneLite. RuneLite won't start after the error notifications
The official oldschool client works fine, RS3 also starts without a hitch.

![image](https://github.com/user-attachments/assets/529d82e9-2165-4aa5-af07-87dc104f353e)
![image](https://github.com/user-attachments/assets/8a890710-12bc-49ea-9c36-595343abb3fa)

Java version:
![image](https://github.com/user-attachments/assets/ee49c4e6-1662-4566-9a68-a99956908ac2)

I even tried linking the Runelite.jar in the settings

Not sure where to go from here

**Comment by Adamcake** [comment]
Java 1.8 is a very very old version, I don't know if runelite these days would be expected to work with that. But to be sure you could try running `java -jar runelite.jar` from the directory where Bolt has saved it, and if that doesn't work, that rules out any issue with the launcher.

Either way I'd suggest to get a newer Java version. Try one of these: https://learn.microsoft.com/en-us/java/openjdk/download#openjdk-21

**Comment by EytanMorg** [comment]
the version I'm showing is the version number I get after Installing Version 8 Update 431 which was released  15 October 2024.

Ill let you know if installing JDK 21 works

**Comment by EytanMorg** [comment]
yep that was the issue, I was using JSE instead of JDK
