### ISSUE TITLE
No elements showing up in Bolt launcher, can't find any error messages either

### ISSUE THREAD

**Issue by ajaypillay** [Adamcake/Bolt#99]
Hi, I'm on Fedora 40. Bolt has been working fine, but now nothing shows up in the window. I uninstalled Bolt with `flatpak uninstall com.adamcake.Bolt` and reinstalled it with `flatpak install com.adamcake.Bolt`, but the issue persists. I tried to locate some log for any Chromium browser errors but couldn't find any in `~/.var/app/com.adamcake.Bolt`. I couldn't find any errors in general in any of the log files I looked through either. How should I go about solving this?

![image](https://github.com/user-attachments/assets/2d22cbc3-63fd-4fd5-a840-d15567e0b0d5)

**Comment by Adamcake** [comment]
Try this: `rm -r .var/app/com.adamcake.Bolt/data/bolt-launcher/CefCache/`

**Comment by Jookia** [comment]
```rm -r ~/.var/app/com.adamcake.Bolt/data/bolt-launcher/CefCache/GPUCache``` does indeed fix it. I think this might have been corrupted by Flatpak's latest Mesa update.

**Comment by ajaypillay** [comment]
Yes, the above fixed it for me. Thanks!
